### ISSUE TITLE
How to integrate into actual softkeyboard

### ISSUE THREAD

**Issue by thetlwinaung** [ROKOLabs/ROKO.Stickers-Android#2]
Does anyone knows how to integrate this project into the actual softkeyboard? I mean not the stock keyboard (AOSP), but the custom softkeyboard sample provided in the legacy android sdk.

**Comment by sselin** [comment]
Hi, please take a look at https://github.com/ROKOLabs/ROKOmoji.Emoji.Keyboard.App-Android - pretty much does exactly that. If you have any questions, please ping help@rokolabs.com
